CREATE DATABASE PRUEBA_SERVICIO;
USE PRUEBA_SERVICIO;

-- DROP DATABASE PRUEBA_SERVICIO;

CREATE TABLE USUARIOS(
	id INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT pk_id PRIMARY KEY(id),
    email VARCHAR(150) NOT NULL,
    CONSTRAINT uq_email UNIQUE(email),
    password VARCHAR(255) NOT NULL
);
SELECT *  FROM USUARIOS;
INSERT INTO USUARIOS(email, password) VALUES('Jazziel@gmail.com', '12345');
INSERT INTO USUARIOS(email, password) VALUES('martin@gmail.com', '12345');
INSERT INTO USUARIOS(email, password) VALUES('ricardo@gmail.com', '12345');
INSERT INTO USUARIOS(email, password) VALUES('jorge@gmail.com', '12345');

CREATE TABLE TAREAS(
	id INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT pk_id PRIMARY KEY(id),
    nombre VARCHAR(50) NOT NULL,
    CONSTRAINT uq_nombre UNIQUE(nombre),
    descripcion VARCHAR(255)
);

INSERT INTO TAREAS(nombre, descripcion) VALUES('INVESTIGACION', 'AAAAAAAAAAAAAAAAAAAAA');
INSERT INTO TAREAS(nombre, descripcion) VALUES('EJEMPLOS', 'AAAAAAAAAAAAAAAAAAAAA');
INSERT INTO TAREAS(nombre, descripcion) VALUES('TEORIA', 'AAAAAAAAAAAAAAAAAAAAA');


CREATE TABLE USUARIOS_TAREAS(
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    id_usuario INT,
    CONSTRAINT fk_id_usuario FOREIGN KEY(id_usuario) REFERENCES USUARIOS(id) ON DELETE CASCADE ON UPDATE CASCADE,
    id_tarea INT,
    CONSTRAINT fk_id_tarea FOREIGN KEY(id_tarea) REFERENCES TAREAS(id) ON DELETE CASCADE ON UPDATE CASCADE
);


INSERT INTO USUARIOS_TAREAS(id_usuario, id_tarea) VALUES(1, 1);
INSERT INTO USUARIOS_TAREAS(id_usuario, id_tarea) VALUES(1, 2);
INSERT INTO USUARIOS_TAREAS(id_usuario, id_tarea) VALUES(1, 3);

CREATE TABLE PLANTILLAWORD(
 id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 nombre_empresa VARCHAR(255) NOT NULL,
 direccion VARCHAR(255) NOT NULL,
 municipio VARCHAR(50) NOT NULL,
 provincia VARCHAR(50) NOT NULL,
 cp VARCHAR(5) NOT NULL,
 telefono VARCHAR(10) NOT NULL
);
SELECT *  FROM PLANTILLAWORD;
SHOW TABLES;
INSERT INTO PLANTILLAWORD(nombre_empresa,direccion,municipio,provincia,cp,telefono) VALUES("tacospp","asdasdad","LPZ", "ASASASSAAS", "13465", "6123548579");